"""Agregar nombre_cliente y bodega a Turno

Revision ID: 27dbf9fb5750
Revises: b72118a77d19
Create Date: 2025-08-26 15:17:54.151091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dbf9fb5750'
down_revision = 'b72118a77d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_cliente', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bodega', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_column('bodega')
        batch_op.drop_column('nombre_cliente')

    # ### end Alembic commands ###
