"""Agregar nombre_cliente y bodega a Turno

Revision ID: 3adc641c0fbb
Revises: 27dbf9fb5750
Create Date: 2025-08-26 16:32:05.286499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3adc641c0fbb'
down_revision = '27dbf9fb5750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('nombre_cliente',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('bodega',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('bodega',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nombre_cliente',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
