"""Base inicial

Revision ID: bd7d1ccce000
Revises: 
Create Date: 2025-08-27 08:15:03.445768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7d1ccce000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=True),
    sa.Column('bodega', sa.String(length=100), nullable=True),
    sa.Column('modulo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('esperando', 'llamado', 'atendido', name='estado_turno', native_enum=False), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('turnos')
    # ### end Alembic commands ###
